### ISSUE TITLE
Unable to parse /react-bootstrap-tooltip-button/lib/TooltipButton.css

### ISSUE THREAD

**Issue by kamarajuPrathi** [pastaclub/react-bootstrap-tooltip-button#2]
It should convert to css right ?
You may need an appropriate loader to handle this file type.
| .tooltip-button-helper {
|   display: inline-block;
|   vertical-align: top;
    at Object.defineProperty.value (bundle.js:155810)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:155868)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:155724)
    at __webpack_require__ (bundle.js:20)
    at Object.canUseDOM (bundle.js:27168)
    at __webpack_require__ (bundle.js:20)
    at Object.defineProperty.value (bundle.js:95219)
    at __webpack_require__ (bundle.js:20)

**Comment by pastaclub** [comment]
Sorry, it is not clear to me what you are doing and where you get an error. Are you only trying to use the component in a project, or trying to re-compile it? Yes, when you run `npm install`, it should build the CSS from the SASS source. What happens when you install the package?

**Comment by kamarajuPrathi** [comment]
After I install and try to use I got that error in console . And after that I tried to add css-loader . It works fine . But it's having issue when I am loading the component during enzyme  testcases .

**Comment by kamarajuPrathi** [comment]
@pastaclub Can you change your css file to .less extension instead of sass .sass is having issues with jest library

**Comment by pastaclub** [comment]
Oh I see. I guess that depends on your webpack configuration and you do need a CSS loader (which is included by default if using react-tools). If you don't want to use one, you could include the CSS as an HTML tag in your index.html, but I think it's easier to do it through WebPack.

I don't use LESS, but you could fork the repository and even use an automatic SASS to LESS converter.
